### ISSUE TITLE
How can I get the visualization results in Figure 3 of the paper?

### ISSUE THREAD

**Issue by harrylin-hyl** [orrzohar/PROB#11]
How can I get the visualization results in Figure 3 of the paper?
Thanks!

**Comment by orrzohar** [comment]
Hi @harrylin-hyl,

I, unfortunately, do not have the original script I used to produce these figures. You have to filter out the detections, as you have 100 per image. To get the figure 3 visualizations, I:

1. loaded an image
2. got PROB and OWOD predictions
3. cycled through the GT (both known and unknown) objects, and if a model had a prediction of the same class/IoU>0.5, I added that bbox on the image

I did this for all the qualitative visualizations in the paper. If you have an issue with this, let me know & I can try finding that script again. 
Best,
Orr

**Comment by harrylin-hyl** [comment]
Hello Orr,

Thanks for your detailed and timely reply!
I have implemented the visualization code and got the following results selected by thresholds ( 0.3 for known and 0.5 for unknown). It seems that there are many unknowns with high confidence and they are even overlapping the GT. Is this result normal? I think it is not practical using GT for visualization, although  the display becomes better. 
 
![1](https://user-images.githubusercontent.com/26209785/226620522-704e97f7-6fc4-46e0-98d4-ffd6ea337e40.jpg)
![2](https://user-images.githubusercontent.com/26209785/226621696-3612c741-a771-4843-b197-730c485af591.jpg)

Best regards,
harrylin

**Comment by orrzohar** [comment]
Hi harrylin,

I guess the question is whether you are trying to reproduce the figures in the paper or you want to use PROB for actual inference. This is a problem that is very common with DETR-type model visualizations and stems from the hard 100 predictions per image + the way voc mAP penalizes these detections. 

An easy way to overcome unknown overconfidence is to down weight the unknown object confidence. You want that, for GT objects, the known object is more confident than the unknown prediction. I ended up using the GT overlap method I described, so this was not necessary. 

I would say:

a. If you want to reproduce the figures from the paper, use the GT method I described.
b. If you want to use PROB for inference, I would add a second step, like NMS, that filters unknowns with high gIOU with detected known objects.

I hope this helps,
Orr

**Comment by harrylin-hyl** [comment]
Hi Orr,

Thanks for your patient reply! This is very helpful, thanks.

Best regards,
harrylin

**Comment by BigBuffa1o** [comment]
> Hello Orr,
> 
> Thanks for your detailed and timely reply! I have implemented the visualization code and got the following results selected by thresholds ( 0.3 for known and 0.5 for unknown). It seems that there are many unknowns with high confidence and they are even overlapping the GT. Is this result normal? I think it is not practical using GT for visualization, although the display becomes better.
> 
> ![1](https://user-images.githubusercontent.com/26209785/226620522-704e97f7-6fc4-46e0-98d4-ffd6ea337e40.jpg) ![2](https://user-images.githubusercontent.com/26209785/226621696-3612c741-a771-4843-b197-730c485af591.jpg)
> 
> Best regards, harrylin

hi bro,can you help share the inference file?Thanks in advance!!

**Comment by BigBuffa1o** [comment]
> Hi @harrylin-hyl,
> 
> I, unfortunately, do not have the original script I used to produce these figures. You have to filter out the detections, as you have 100 per image. To get the figure 3 visualizations, I:
> 
> 1. loaded an image
> 2. got PROB and OWOD predictions
> 3. cycled through the GT (both known and unknown) objects, and if a model had a prediction of the same class/IoU>0.5, I added that bbox on the image
> 
> I did this for all the qualitative visualizations in the paper. If you have an issue with this, let me know & I can try finding that script again. Best, Orr

get some problem for finding unkown object by trying to visualize the result,i get thounds of unknown object with high scores, can you update a inference script of actual inference(not using GT for filering unknown) for reproducing the paper result?

After i train on custom dataset and it turns out there are still many unknown object even after NMS,and they have high confidence,like in this photo
![image](https://user-images.githubusercontent.com/118952497/234502770-c694496b-5f54-49ba-894e-1f48f76ae5fb.png)

Thank you so much!

**Comment by ae208gpu** [comment]
Hello @BigBuffa1o, @harrylin-hyl please would share the visualization code that you have.

**Comment by FoRGEU** [comment]
Hi, @harrylin-hyl @BigBuffa1o  Could you share the visualization code that you have with me？Thank you.

**Comment by YH-2023** [comment]
@FoRGEU @ae208gpu @BigBuffa1o @harrylin-hyl 
Can you share the visualization code?

**Comment by 2665207323** [comment]
@orrzohar  Hello, I cannot complete the visualization part alone. Can you share the source code of your visualization part? Thank you so much.

**Comment by eightnight2049** [comment]
> Hello Orr,
> 
> Thanks for your detailed and timely reply! I have implemented the visualization code and got the following results selected by thresholds ( 0.3 for known and 0.5 for unknown). It seems that there are many unknowns with high confidence and they are even overlapping the GT. Is this result normal? I think it is not practical using GT for visualization, although the display becomes better.
> 
> ![1](https://user-images.githubusercontent.com/26209785/226620522-704e97f7-6fc4-46e0-98d4-ffd6ea337e40.jpg) ![2](https://user-images.githubusercontent.com/26209785/226621696-3612c741-a771-4843-b197-730c485af591.jpg)
> 
> Best regards, harrylin

Hello harrylin, 
    Could you please share your code for the visualization of the prob project? Thank you very much.
Best regards
