### ISSUE TITLE
What's the meaning of `matched objects` and `unmatched objects`?

### ISSUE THREAD

**Issue by luomingshuang** [orrzohar/PROB#14]
Hi, @orrzohar , thanks for your great work.

Here, I have some questions about your paper as follows:
1. what's the meaning of `matched objects`? Do them refer to the pairs of output embedding and its relative annotated labels (labels and boxes supervision)?

2. How to get the un-known objects bounding box after training?

**Comment by orrzohar** [comment]
Hi @luomingshuang,

1.  Yes, exactly, matched queries/object proposals are query embedding/proposals that were matched to one of the GT objects via the Hungarian matching function (~had high overlap with GT box/label)
2. To get the unknown object bboxes you need to filter out the boxes with the label '80'

Best,
Orr

**Comment by luomingshuang** [comment]
Cool，thanks.

**Comment by luomingshuang** [comment]
Em, hi @orrzohar , another question is that all the boxes (including unknow objects and class-known objects) are generated by the  f_bbox head when inference? So in the training stage, the unkown objects also have the GT boxes supervision while they don't have GT class labels?

**Comment by orrzohar** [comment]
Hi @luomingshuang,
The f_bbox head generates both unknown and known bounding boxes but only has _known_ object supervision, i.e., in training, there is **no GT box supervision for unknown objects** (this would violate the open world assumption. see datasets/torchvision/open_world, where all cls_ids not in the known range are filtered out). 

This is a task of generalization and learning to detect _unknown/novel_ objects given only _known/labeled_ object supervision. Essentially, the f_bbox head needs to learn to localize all the objects in an image given only partial labeling, and the cls head learns to classify each proposal into either a known class, background, or unknown object.

**Comment by luomingshuang** [comment]
Thanks a lot.
