### ISSUE TITLE
Visualization code for running inference

### ISSUE THREAD

**Issue by ae208gpu** [orrzohar/PROB#20]
Hello, 
I am looking to work with your model and have been able to run and train the model, it would be really helpful if you could share the inference script that was used to get the results. 

@orrzohar @harrylin-hyl @BigBuffa1o

**Comment by ae208gpu** [comment]
Hi, I have not been able to the code together for inference and am facing some issues. Please would you update the inference code it will be really helpful. @orrzohar @harrylin-hyl @BigBuffa1o

**Comment by orrzohar** [comment]
Hello @ae208gpu,
Apologies for the delay. I have a deadline next week, but I'll prioritize helping you once that's done. 
Best,
Orr

**Comment by ae208gpu** [comment]
Thank you so much @orrzohar!

**Comment by orrzohar** [comment]
Hi @ae208gpu,

Were you able to utilize the scripts in #21? 
If not, what did you come across that was an issue?

Best,
Orr
