### ISSUE TITLE
Some questions about Visualization for known and unknown objects

### ISSUE THREAD

**Issue by luomingshuang** [orrzohar/PROB#21]
Hi, @orrzohar , thanks for your great job. Here, I have some questions about visualization for known and unknown objects.

My codes for visualization as follows:
```

from torchvision.ops.boxes import batched_nms

### You can choose confidence: the default value of confidence is 0.7
def filter_boxes(scores, boxes, confidence=0.7, apply_nms=True, iou=0.5):
    keep = scores.max(-1).values > confidence
    scores, boxes = scores[keep], boxes[keep]
 
    if apply_nms:
        top_scores, labels = scores.max(-1)
        keep = batched_nms(boxes, top_scores, labels, iou)
        scores, boxes = scores[keep], boxes[keep]
 
    return scores, boxes

@torch.no_grad()
def viz(model, criterion, postprocessors, data_loader, base_ds, device, output_dir, args):
    dataset = args.dataset
    import numpy as np
    os.makedirs(output_dir, exist_ok=True)
    model.eval()
    criterion.eval()
 
    metric_logger = utils.MetricLogger(delimiter="  ")
    metric_logger.add_meter('class_error', utils.SmoothedValue(window_size=1, fmt='{value:.2f}'))

    use_topk = True
    num_obj = 20
    for batch_idx, (samples, targets) in enumerate(tqdm(data_loader)):
        if batch_idx >=10:
            break
        samples = samples.to(device)
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]
        top_k = len(targets[0]['boxes'])

        # outputs = model(samples)
        # indices = outputs['pred_logits'][0].softmax(-1)[..., 1].sort(descending=True)[1][:top_k]
        # predicted_boxes = torch.stack([outputs['pred_boxes'][0][i] for i in indices])
        # logits = torch.stack([outputs['pred_logits'][0][i] for i in indices])
        # scores_softmax = logits.softmax(-1)[:, :-1]
        # labels = scores_softmax.argmax(axis=1)
        # scores = scores_softmax.max(-1).values

        outputs = model(samples)
        # probas = outputs['pred_logits'].softmax(-1)[0, :, :-1].cpu()
        probas = outputs['pred_logits'].softmax(-1)[0, :, :].cpu()
        pred_objs = outputs['pred_obj'].softmax(-1)[0, :].cpu()
        predicted_boxes = outputs['pred_boxes'][0,].cpu()
        scores, predicted_boxes = filter_boxes(probas, predicted_boxes)
        labels = scores.argmax(axis=1)
        scores = scores.max(-1).values

        fig, ax = plt.subplots(1, 3, figsize=(10,3), dpi=200)
    
        # Ori Picture
        plot_ori_image(
            samples.tensors[0:1],
            ax[0], 
            plot_prob=False,
        )
        ax[0].set_title('Original Image')

        # Pred results
        # if not control the number of labels
        if not use_topk:
            plot_prediction(
                samples.tensors[0:1], 
                scores[-num_obj:], 
                predicted_boxes[-num_obj:], 
                labels[-num_obj:], 
                ax[1], 
                plot_prob=False,
                dataset=dataset,
            )
        # if control the number of labels
        if use_topk:
            plot_prediction(
                samples.tensors[0:1], 
                scores[-top_k:], 
                predicted_boxes[-top_k:], 
                labels[-top_k:], 
                ax[1], 
                plot_prob=False,
                dataset=dataset,
            )
        ax[1].set_title('Prediction (Ours)')
 
        # GT Results
        plot_prediction(
            samples.tensors[0:1], 
            torch.ones(targets[0]['boxes'].shape[0]), 
            targets[0]['boxes'], 
            targets[0]['labels'],
            ax[2], 
            plot_prob=False,
            dataset=dataset,
        )
        ax[2].set_title('GT')
 
        for i in range(3):
            ax[i].set_aspect('equal')
            ax[i].set_axis_off()
 
        plt.savefig(os.path.join(output_dir, f'img_{int(targets[0]["image_id"][0])}.jpg'))
```
There are some results for visualization:
when I set `probas = outputs['pred_logits'].softmax(-1)[0, :, :-1].cpu()`, (In this case, there will be just known objects (because it just considers 0-79 known classes.)):
![e26d9e8d374a2cac3f2c8921bac7cf6](https://github.com/orrzohar/PROB/assets/37799481/d9ba25ec-a3cd-422c-a51d-ca0950d66ed3)
![d7174a3087a046c61ea85014b714d6e](https://github.com/orrzohar/PROB/assets/37799481/c2a398c1-cf21-432c-bc42-17901894aecc)

when I set `probas = outputs['pred_logits'].softmax(-1)[0, :, :].cpu()`, (In this case, there will be known and unknown objects (because it just considers 0-80 known classes.)):
![cb0a0b00cfe7adbe7690c9846ea0512](https://github.com/orrzohar/PROB/assets/37799481/17faf44e-140e-44f1-b0e5-8b4c84e5e624)
![00f0524fe1f3d7b97af23f90ad75874](https://github.com/orrzohar/PROB/assets/37799481/bcb12474-d6c2-4c2b-a9a3-8908be52c3a5)

When I show the boxes of known and unknown objects in the picture, we can see that there are many overlap boxes on known objects and many boxes which are not objectness, so can you tell me how to modify the code and make it normal?

**Comment by ae208gpu** [comment]
@luomingshuang what is plot prediction function here ?

**Comment by ae208gpu** [comment]
Please could you share your inference script.

**Comment by luomingshuang** [comment]
```
def plot_prediction(image, scores, boxes, labels, ax=None, plot_prob=True, dataset='OWOD'):    
    if ax is None:
        ax = plt.gca()
    plot_results(image[0].permute(1, 2, 0).detach().cpu().numpy(), scores, boxes, labels, ax, plot_prob=plot_prob, dataset=dataset)

def plot_results(pil_img, scores, boxes, labels, ax, plot_prob=True, norm=True, dataset='OWOD'):
    from matplotlib import pyplot as plt
    h, w = pil_img.shape[:-1]
    # w, h = pil_img.shape[:-1]
    image = plot_image(ax, pil_img, norm)
    colors = COLORS * 100
    if boxes is not None:
        # boxes = [rescale_bboxes(boxes[i], [w, h]).cpu() for i in range(len(boxes))]
        for sc, cl, (xmin, ymin, xmax, ymax), c in zip(scores, labels, boxes, colors):
            ax.add_patch(plt.Rectangle((xmin, ymin), xmax - xmin, ymax - ymin,
                                       fill=False, color=c, linewidth=2))
            
            text = f'{CLASSES[str(dataset)][cl]}: {sc:0.2f}'
            ax.text(xmin, ymin, text, fontsize=5, bbox=dict(facecolor='yellow', alpha=0.5))
    ax.grid('off')
```

**Comment by luomingshuang** [comment]
Add rescale_boxes to viz:
```
        probas = outputs['pred_logits'].softmax(-1)[0, :, :].cpu()
        predicted_boxes = outputs['pred_boxes'][0,].cpu()
        predicted_boxes = rescale_bboxes(predicted_boxes.cpu(), [w, h])
        scores, predicted_boxes = filter_boxes(probas, predicted_boxes)
        labels = scores.argmax(axis=1)
        scores = scores.max(-1).values
```

**Comment by ae208gpu** [comment]
Thank you so much @luomingshuang, really appreciate your quick response!

**Comment by luomingshuang** [comment]
Em, but I think there are still some errors in my above codes for visualizing.

**Comment by ae208gpu** [comment]
I am not able to generate the images that you have shown

**Comment by ae208gpu** [comment]
How is your main module defined?

**Comment by ae208gpu** [comment]
how were you able to get those images, do I need to add viz to plot_utils.py?

**Comment by luomingshuang** [comment]
You can have a reference about https://github.com/akshitac8/OW-DETR/blob/main/engine.py .

**Comment by ae208gpu** [comment]
Thanks @luomingshuang will check it out

**Comment by orrzohar** [comment]
Hi @luomingshuang,

I believe I rejected proposals with high overlap with 'known' object predictions - it was my observation that known object were predicted with relatively high accuracy. Please note that you may lose some unknown object predictions in this case.  Please note that the visualizations in the figures were not generated this way, but relied on the GT objects (See Issue #11).

If this is still an issue, please reopen and let me know what you need help with,

Best,
Orr

**Comment by YH-2023** [comment]
@ae208gpu @luomingshuang 
Did you solve it? Can you share the visualization code?

**Comment by simranbajaj06** [comment]
Do we need to change the content of EVAL_M_OWOD_BENCHMARK.sh ?

I am getting this

Initialized from the pre-training model
<All keys matched successfully>
  0%|                                                                                                            | 0/5123 [00:00<?, ?it/s]/home/ubuntu/labellerr/PROB/models/position_encoding.py:49: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature ** (2 * (dim_t // 2) / self.num_pos_feats)
/home/ubuntu/miniconda3/envs/prob/lib/python3.10/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|▏                                                                                                  | 10/5123 [00:05<47:31,  1.79it/s]
Warning: Dataset 'TOWOD' not found in CLASSES.
Warning: Dataset 'TOWOD' not found in CLASSES.

I am trying to get direct inference and i had added the viz method 

after run bash configs/EVAL_M_OWOD_BENCHMARK.sh
@luomingshuang @orrzohar

**Comment by eightnight2049** [comment]
> 嗨， 感谢您的出色工作。在这里，我有一些关于已知和未知对象的可视化的问题。
> 
> 我的可视化代码如下：
> 
> ```
> 
> from torchvision.ops.boxes import batched_nms
> 
> ### You can choose confidence: the default value of confidence is 0.7
> def filter_boxes(scores, boxes, confidence=0.7, apply_nms=True, iou=0.5):
>     keep = scores.max(-1).values > confidence
>     scores, boxes = scores[keep], boxes[keep]
>  
>     if apply_nms:
>         top_scores, labels = scores.max(-1)
>         keep = batched_nms(boxes, top_scores, labels, iou)
>         scores, boxes = scores[keep], boxes[keep]
>  
>     return scores, boxes
> 
> @torch.no_grad()
> def viz(model, criterion, postprocessors, data_loader, base_ds, device, output_dir, args):
>     dataset = args.dataset
>     import numpy as np
>     os.makedirs(output_dir, exist_ok=True)
>     model.eval()
>     criterion.eval()
>  
>     metric_logger = utils.MetricLogger(delimiter="  ")
>     metric_logger.add_meter('class_error', utils.SmoothedValue(window_size=1, fmt='{value:.2f}'))
> 
>     use_topk = True
>     num_obj = 20
>     for batch_idx, (samples, targets) in enumerate(tqdm(data_loader)):
>         if batch_idx >=10:
>             break
>         samples = samples.to(device)
>         targets = [{k: v.to(device) for k, v in t.items()} for t in targets]
>         top_k = len(targets[0]['boxes'])
> 
>         # outputs = model(samples)
>         # indices = outputs['pred_logits'][0].softmax(-1)[..., 1].sort(descending=True)[1][:top_k]
>         # predicted_boxes = torch.stack([outputs['pred_boxes'][0][i] for i in indices])
>         # logits = torch.stack([outputs['pred_logits'][0][i] for i in indices])
>         # scores_softmax = logits.softmax(-1)[:, :-1]
>         # labels = scores_softmax.argmax(axis=1)
>         # scores = scores_softmax.max(-1).values
> 
>         outputs = model(samples)
>         # probas = outputs['pred_logits'].softmax(-1)[0, :, :-1].cpu()
>         probas = outputs['pred_logits'].softmax(-1)[0, :, :].cpu()
>         pred_objs = outputs['pred_obj'].softmax(-1)[0, :].cpu()
>         predicted_boxes = outputs['pred_boxes'][0,].cpu()
>         scores, predicted_boxes = filter_boxes(probas, predicted_boxes)
>         labels = scores.argmax(axis=1)
>         scores = scores.max(-1).values
> 
>         fig, ax = plt.subplots(1, 3, figsize=(10,3), dpi=200)
>     
>         # Ori Picture
>         plot_ori_image(
>             samples.tensors[0:1],
>             ax[0], 
>             plot_prob=False,
>         )
>         ax[0].set_title('Original Image')
> 
>         # Pred results
>         # if not control the number of labels
>         if not use_topk:
>             plot_prediction(
>                 samples.tensors[0:1], 
>                 scores[-num_obj:], 
>                 predicted_boxes[-num_obj:], 
>                 labels[-num_obj:], 
>                 ax[1], 
>                 plot_prob=False,
>                 dataset=dataset,
>             )
>         # if control the number of labels
>         if use_topk:
>             plot_prediction(
>                 samples.tensors[0:1], 
>                 scores[-top_k:], 
>                 predicted_boxes[-top_k:], 
>                 labels[-top_k:], 
>                 ax[1], 
>                 plot_prob=False,
>                 dataset=dataset,
>             )
>         ax[1].set_title('Prediction (Ours)')
>  
>         # GT Results
>         plot_prediction(
>             samples.tensors[0:1], 
>             torch.ones(targets[0]['boxes'].shape[0]), 
>             targets[0]['boxes'], 
>             targets[0]['labels'],
>             ax[2], 
>             plot_prob=False,
>             dataset=dataset,
>         )
>         ax[2].set_title('GT')
>  
>         for i in range(3):
>             ax[i].set_aspect('equal')
>             ax[i].set_axis_off()
>  
>         plt.savefig(os.path.join(output_dir, f'img_{int(targets[0]["image_id"][0])}.jpg'))
> ```
> 
> 可视化有一些结果：当我设置 时，（在本例中，将只有已知对象（因为它只考虑 0-79 个已知类。`probas = outputs['pred_logits'].softmax(-1)[0, :, :-1].cpu()` ![e26d9e8d374a2cac3f2c8921bac7cf6](https://github.com/orrzohar/PROB/assets/37799481/d9ba25ec-a3cd-422c-a51d-ca0950d66ed3) ![d7174a3087a046c61ea85014b714d6e](https://github.com/orrzohar/PROB/assets/37799481/c2a398c1-cf21-432c-bc42-17901894aecc)
> 
> 当我设置 时（在这种情况下，会有已知和未知的对象（因为它只考虑 0-80 个已知类。`probas = outputs['pred_logits'].softmax(-1)[0, :, :].cpu()` ![cb0a0b00cfe7adbe7690c9846ea0512](https://github.com/orrzohar/PROB/assets/37799481/17faf44e-140e-44f1-b0e5-8b4c84e5e624) ![00f0524fe1f3d7b97af23f90ad75874](https://github.com/orrzohar/PROB/assets/37799481/bcb12474-d6c2-4c2b-a9a3-8908be52c3a5)
> 
> 当我在图片中展示已知和未知对象的框时，我们可以看到已知对象上有很多重叠的框，也有很多不是对象的框，那么你能告诉我如何修改代码并使其正常吗？



> Hi, [@orrzohar](https://github.com/orrzohar) , thanks for your great job. Here, I have some questions about visualization for known and unknown objects.
> 
> My codes for visualization as follows:
> 
> ```
> 
> from torchvision.ops.boxes import batched_nms
> 
> ### You can choose confidence: the default value of confidence is 0.7
> def filter_boxes(scores, boxes, confidence=0.7, apply_nms=True, iou=0.5):
>     keep = scores.max(-1).values > confidence
>     scores, boxes = scores[keep], boxes[keep]
>  
>     if apply_nms:
>         top_scores, labels = scores.max(-1)
>         keep = batched_nms(boxes, top_scores, labels, iou)
>         scores, boxes = scores[keep], boxes[keep]
>  
>     return scores, boxes
> 
> @torch.no_grad()
> def viz(model, criterion, postprocessors, data_loader, base_ds, device, output_dir, args):
>     dataset = args.dataset
>     import numpy as np
>     os.makedirs(output_dir, exist_ok=True)
>     model.eval()
>     criterion.eval()
>  
>     metric_logger = utils.MetricLogger(delimiter="  ")
>     metric_logger.add_meter('class_error', utils.SmoothedValue(window_size=1, fmt='{value:.2f}'))
> 
>     use_topk = True
>     num_obj = 20
>     for batch_idx, (samples, targets) in enumerate(tqdm(data_loader)):
>         if batch_idx >=10:
>             break
>         samples = samples.to(device)
>         targets = [{k: v.to(device) for k, v in t.items()} for t in targets]
>         top_k = len(targets[0]['boxes'])
> 
>         # outputs = model(samples)
>         # indices = outputs['pred_logits'][0].softmax(-1)[..., 1].sort(descending=True)[1][:top_k]
>         # predicted_boxes = torch.stack([outputs['pred_boxes'][0][i] for i in indices])
>         # logits = torch.stack([outputs['pred_logits'][0][i] for i in indices])
>         # scores_softmax = logits.softmax(-1)[:, :-1]
>         # labels = scores_softmax.argmax(axis=1)
>         # scores = scores_softmax.max(-1).values
> 
>         outputs = model(samples)
>         # probas = outputs['pred_logits'].softmax(-1)[0, :, :-1].cpu()
>         probas = outputs['pred_logits'].softmax(-1)[0, :, :].cpu()
>         pred_objs = outputs['pred_obj'].softmax(-1)[0, :].cpu()
>         predicted_boxes = outputs['pred_boxes'][0,].cpu()
>         scores, predicted_boxes = filter_boxes(probas, predicted_boxes)
>         labels = scores.argmax(axis=1)
>         scores = scores.max(-1).values
> 
>         fig, ax = plt.subplots(1, 3, figsize=(10,3), dpi=200)
>     
>         # Ori Picture
>         plot_ori_image(
>             samples.tensors[0:1],
>             ax[0], 
>             plot_prob=False,
>         )
>         ax[0].set_title('Original Image')
> 
>         # Pred results
>         # if not control the number of labels
>         if not use_topk:
>             plot_prediction(
>                 samples.tensors[0:1], 
>                 scores[-num_obj:], 
>                 predicted_boxes[-num_obj:], 
>                 labels[-num_obj:], 
>                 ax[1], 
>                 plot_prob=False,
>                 dataset=dataset,
>             )
>         # if control the number of labels
>         if use_topk:
>             plot_prediction(
>                 samples.tensors[0:1], 
>                 scores[-top_k:], 
>                 predicted_boxes[-top_k:], 
>                 labels[-top_k:], 
>                 ax[1], 
>                 plot_prob=False,
>                 dataset=dataset,
>             )
>         ax[1].set_title('Prediction (Ours)')
>  
>         # GT Results
>         plot_prediction(
>             samples.tensors[0:1], 
>             torch.ones(targets[0]['boxes'].shape[0]), 
>             targets[0]['boxes'], 
>             targets[0]['labels'],
>             ax[2], 
>             plot_prob=False,
>             dataset=dataset,
>         )
>         ax[2].set_title('GT')
>  
>         for i in range(3):
>             ax[i].set_aspect('equal')
>             ax[i].set_axis_off()
>  
>         plt.savefig(os.path.join(output_dir, f'img_{int(targets[0]["image_id"][0])}.jpg'))
> ```
> 
> There are some results for visualization: when I set `probas = outputs['pred_logits'].softmax(-1)[0, :, :-1].cpu()`, (In this case, there will be just known objects (because it just considers 0-79 known classes.)): ![e26d9e8d374a2cac3f2c8921bac7cf6](https://github.com/orrzohar/PROB/assets/37799481/d9ba25ec-a3cd-422c-a51d-ca0950d66ed3) ![d7174a3087a046c61ea85014b714d6e](https://github.com/orrzohar/PROB/assets/37799481/c2a398c1-cf21-432c-bc42-17901894aecc)
> 
> when I set `probas = outputs['pred_logits'].softmax(-1)[0, :, :].cpu()`, (In this case, there will be known and unknown objects (because it just considers 0-80 known classes.)): ![cb0a0b00cfe7adbe7690c9846ea0512](https://github.com/orrzohar/PROB/assets/37799481/17faf44e-140e-44f1-b0e5-8b4c84e5e624) ![00f0524fe1f3d7b97af23f90ad75874](https://github.com/orrzohar/PROB/assets/37799481/bcb12474-d6c2-4c2b-a9a3-8908be52c3a5)
> 
> When I show the boxes of known and unknown objects in the picture, we can see that there are many overlap boxes on known objects and many boxes which are not objectness, so can you tell me how to modify the code and make it normal?

Hello, thank you for sharing the code for the prob project visualization. I have also used your code, and the current visualization results are as follows, which seem quite unsatisfactory. Do you have the latest visualization code? If you could share it, I would greatly appreciate it.

![Image](https://github.com/user-attachments/assets/1e34c93e-2047-4731-830e-7769fab9b729)
