### ISSUE TITLE
About the Understanding of the Paper

### ISSUE THREAD

**Issue by Rzx520** [orrzohar/PROB#23]
How to distinguish between mismatched backgrounds and unknown objects when penalizing matched Mahalanobis distances?

**Comment by Rzx520** [comment]
@orrzohar That is to say, I want to know how the module for objectness determination distinguishes unknown objects from the background?

**Comment by orrzohar** [comment]
Hi @Rzx520,
I only penalize Mahalanobis distance of **matched** query embeddings, i.e., embeddings that were matched to a GT object via the Hungarian matching. I recently uploaded a [video explaining how PROB works](https://www.youtube.com/watch?v=prSeAoO82M4&t=1s). Hopefully, it will be helpful as well.

Does that answer your question?
Best,
Orr
