### ISSUE TITLE
About my training

### ISSUE THREAD

**Issue by Yzhongming** [orrzohar/PROB#24]
Hello, I would like to ask about my training progress on Task1. I have trained for several epochs, but the class_error has remained at 100.00. Is this normal?

**Comment by orrzohar** [comment]
Hi @Yzhongming,
No, it isn't - I attached a picture of the class error over a few runs with different hyperparameters. It drops pretty quickly in the beginning.
![class_error_unscaled](https://github.com/orrzohar/PROB/assets/108689663/ff62b22b-da5e-4d85-8672-21940a2631f7)

Best,
Orr
