### ISSUE TITLE
CUDA Out of Memory

### ISSUE THREAD

**Issue by AmingWu** [orrzohar/PROB#31]
Dear authors,

When I run python test.py, there is an error: Cuda out of memory. Could I use multiple GPUs to run this command?

**Comment by orrzohar** [comment]
Hi @AmingWu,

You can, but the test.py is only used to verify that the deformable attention is compiled correctly. It basically tests the performance of transformers with varying numbers of tokens (N). 

**As long as the tests for the number of tokens (N) were OK, then this will not affect the rest of your results at all and I really wouldn't bother trying to run this on multiple GPUs.** 

Best,
Orr
