### ISSUE TITLE
Inference?

### ISSUE THREAD

**Issue by sf-pear** [orrzohar/PROB#34]
Hi Orr,

I managed to train task 1 and now I would like to get some predictions on a couple test images. I'm reading through issues trying to figure out what I have to do to run inference, but I'm still confused. How do I get predictions from an image?

**Comment by orrzohar** [comment]
Hi @sf-pear,

To run inference, you can use this snippet from the engine.evaluate:

```
  for samples, targets in metric_logger.log_every(data_loader, 10, header):
      samples = samples.to(device)
       targets = [{k: v.to(device) for k, v in t.items()} for t in targets]
      outputs = model(samples)
      orig_target_sizes = torch.stack([t["orig_size"] for t in targets], dim=0)
      results = postprocessors['bbox'](outputs, orig_target_sizes)
```

You basically just need to load the model and the images and input the image batch into the model. The outputs are then put into the postprocessors['bbox'] to convert them to a list of dictionaries (with one element per image in the input batch).

From here, you can use all 100 predictions/image, or do some post-processing yourself, like NMS, thresholding detections based on confidence, etc., all depending on what your final goal is (this is the identical to what people do when using DDETR/DETR, as at this point the problems are functionally the same).

Best,
Orr

**Comment by orrzohar** [comment]
Hi @sf-pear,

What is your status re. this issue?

Were you able to run inference?

Best,
Orr

**Comment by sf-pear** [comment]
Not yet. Seems like I was able to load the model in a very hacky way (below), but haven't tried to run inference yet. I still need to load the dataset to try it out.

For some context: I'm writing a jupyter notebook with some instructions on how to set up the repo to train PROB on custom data. Ideally, I'd be able to generate annotated images within the notebook using the weights from any task. 

```python
from models import build_model
import numpy as np
import torch

model, criterion, postprocessors, exemplar_selection = build_model(args, mode=args.model_type)

device = torch.device(args.device)

model.to(device)

model_without_ddp = model

def match_name_keywords(n, name_keywords):
    out = False
    for b in name_keywords:
        if b in n:
            out = True
            break
    return out

param_dicts = [
    {
        "params":
            [p for n, p in model_without_ddp.named_parameters()
                if not match_name_keywords(n, args.lr_backbone_names) and not match_name_keywords(n, args.lr_linear_proj_names) and p.requires_grad],
        "lr": args.lr,
    },
    {
        "params": [p for n, p in model_without_ddp.named_parameters() if match_name_keywords(n, args.lr_backbone_names) and p.requires_grad],
        "lr": args.lr_backbone,
    },
    {
        "params": [p for n, p in model_without_ddp.named_parameters() if match_name_keywords(n, args.lr_linear_proj_names) and p.requires_grad],
        "lr": args.lr * args.lr_linear_proj_mult,
    }
]

if args.sgd:
    optimizer = torch.optim.SGD(param_dicts, lr=args.lr, momentum=0.9,
                                weight_decay=args.weight_decay)
else:
    optimizer = torch.optim.AdamW(param_dicts, lr=args.lr,
                                    weight_decay=args.weight_decay)

if args.pretrain:
    print('Initialized from the pre-training model')
    checkpoint = torch.load(args.pretrain, map_location='cpu')
    state_dict = checkpoint['model']
    msg = model_without_ddp.load_state_dict(state_dict, strict=False)
    print(msg)
    args.start_epoch = checkpoint['epoch'] + 1
    if args.eval:
        test_stats, coco_evaluator = evaluate(model, criterion, postprocessors, data_loader_val, base_ds, device, args.output_dir, args)
        #return
```

Any advice on how to do this would be more than welcome!
