### ISSUE TITLE
Train Problem

### ISSUE THREAD

**Issue by AmingWu** [orrzohar/PROB#36]
Dear Authors,

When I train your code, there is a problem. Which choice should I select?

![捕获](https://github.com/orrzohar/PROB/assets/38445175/e7ce4937-d6c0-484b-b73b-c624e0b3db26)

**Comment by orrzohar** [comment]
Hi @AmingWu,

 To use [wandb](https://wandb.ai/), you need to: 

1. create a W&B account.
2. log into your account in the terminal. 

If you prefer not to use wandb, you need to set wandb_project to ""
https://github.com/orrzohar/PROB/blob/09d814353933f8bdfe944c8afd4b57b8416ebc8e/main_open_world.py#L144

also, please uncomment lines 169 and 170 in main_open_world.py

I personally always used wandb, but this should work as well. 

Best,
Orr

**Comment by orrzohar** [comment]
Hi @AmingWu,

I am going to assume that this issue is resolved.

If you are still unable to run training, please re-open this and let me know.

Best,
Orr
