### ISSUE TITLE
VoC Incremental Fine Tune Exemplar Set Used?

### ISSUE THREAD

**Issue by AstroBoy1** [orrzohar/PROB#39]
Hi, I was wondering if you used a VoC Incremental Fine Tune Exemplar Set for each of the three settings and if it's in the repository?

**Comment by orrzohar** [comment]
Hi @AstroBoy1,
The exemplars are selected actively. I, unfortunately, do not have the one I got a year ago, but hopefully, it is not too noisy, and you will get similar results. 

Re iOD results, please see https://github.com/orrzohar/PROB/issues/8

Best,
Orr
