### ISSUE TITLE
Minor installation problems

### ISSUE THREAD

**Issue by AstroBoy1** [orrzohar/PROB#4]
There are a few minor installation problems. The first is when setting up the conda environment, torch packages could not be found. The second is trying to install multiscaledeformableattention before running the make.sh. These two result in errors. The third problem is running coco2voc.py, which will append to the original train.txt file, which is already up to date. It does not result in an error, but would double the train.txt file size.

**Comment by orrzohar** [comment]
Hi @AstroBoy1,
Thank you for pointing out the issues with installation!

I exchanged the .yml file with a much less detailed requirments.txt file. This should improve the reproducibility of the code moving forward by excluding build and unnecessary packages. I also updated the installation instructions and tested on a new instance to make sure it worked. I found no other steps were required to run the evaluation, with the exemption of running chmod +x on some of the bash scripts (I updated the installation accordingly).

I don't use the train.txt file for training, only the t1-t2.txt files in the sub-directories. Feel free to comment out / delete that line, I do not think it will do anything in terms of evaluation/training. 

After installation, were you able to reproduce all the other results?

Best,
Orr
