### ISSUE TITLE
Model selection

### ISSUE THREAD

**Issue by Rzx520** [orrzohar/PROB#40]
> 
> I am happy to help! Yes, these are very similar to the curves I got on my machine: ![image](https://user-images.githubusercontent.com/108689663/251187371-d27f50c7-e232-4826-8712-5e09bc150b24.png)
> 
> I actually looked into why this happens and this has to do with PROB learning a good representation of objectness very early on (which is why U-Recall initially jumps, if you plot U-Recall inside epoch 1 you will see it increase from ~0 to 19). Then, as training progresses, it starts declining as it starts making more known object predictions, and therefore less unknown object predictions (e.g., ~U-Recall@100 goes down to ~U-Recall@80).
> 
> I will update the readme with this hyper parameter setup & machine type for future users.
> 
> If you encounter any new issues - do not hesitate to reach out, Orr

It is indeed like this. We can see that the U_R50 has decreased even after the training time has increased. I am quite puzzled, so why not choose the model with the highest U_R50?  @orrzohar

**Comment by orrzohar** [comment]
Hi @Rzx520,
Notice there is a balance here between K_AP50 and U_R50. I chose the checkpoint I thought was best --although this is somewhat subjective. 

You can select the model with the highest U_R, the them K_AP wouldn't be as high

Best,
Orr

**Comment by Rzx520** [comment]
I understand. Thanks
