### ISSUE TITLE
pred_obj

### ISSUE THREAD

**Issue by Rzx520** [orrzohar/PROB#45]
Is the larger the Pred_obj value output by the model, the lower the objectness, or did I make a mistake?

**Comment by Rzx520** [comment]
![obj](https://github.com/orrzohar/PROB/assets/74809549/48a3088c-6ab6-4a78-8cbf-170995067bf4)
As shown in the figure, 430.17 represents the output pred_obj value of the model, which is considered the largest among 100 obj values. However, the actual predicted obj of the train is indeed very small.@orrzohar

**Comment by Rzx520** [comment]
![obj_true](https://github.com/orrzohar/PROB/assets/74809549/010e7764-f3cc-48e6-a40d-a697b4e8403b)

This pred_obj is only 48.92, am I doing the opposite?@orrzohar

**Comment by orrzohar** [comment]
Hi @Rzx520,

You are not visualizing the objectness but the negative log-likelihood of the objectness. This is why this value is larger than 1 and also why objects have smaller values than background values. To get the final objectness, you need to:

https://github.com/orrzohar/PROB/blob/10b6518f90495e07b7baf0d1bfa353f0e583eb8e/models/prob_deformable_detr.py#L531

This would, of course, make the train have a higher objectness than the background you visualized and normalize it between 0-1.

Best,
Orr
