### ISSUE TITLE
problem of wandb

### ISSUE THREAD

**Issue by lshssel** [orrzohar/PROB#49]
hi, I'm having a 'wandb' issue when running a 'run.sh' file，I found a way not to use wandb in your other answers, and I wonder if not using wandb will have an impact on the experiment，Looking forward to hearing from you.

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql
wandb.errors.CommError: Permission denied, ask the project owner to grant you access
wandb: ERROR Internal wandb error: file data was not synced
Problem at: /home/workspace/prob/main_open_world.py 165 main
wandb.errors.MailboxError: transport failed
wandb: While tearing down the service manager. The following error has occured: [Errno 32] Broken pipe

**Comment by orrzohar** [comment]
Hi @lshssel,

Not using wandb should not affect the performance of the model. However, it does make it more difficult to debug if that is needed (for example if you are training with a different system and different hyperparameters that may be needed).

Best,
Orr

**Comment by lshssel** [comment]
ok, thank you very much!
