### ISSUE TITLE
Task2 Task3 Task4 Is the result obtained from other tasks the best one selected, or is it the result of the last training in each task taken？

### ISSUE THREAD

**Issue by Rzx520** [orrzohar/PROB#51]
![image](https://github.com/orrzohar/PROB/assets/74809549/730d3f4e-117c-4ae5-8785-09f7dde407a6)

**Comment by orrzohar** [comment]
Hi @Rzx520,

I set the hyper parameters such that I maximize the performance of each task. So, with the hyper parameters in the codebase, you should get these results as the last checkpoint in each task. 

When I developed PROB, I of course looked for the optimum in the training curve and set that value as the number of epochs and lr_drop. 

Best,
Orr
