### ISSUE TITLE
WI and AOSE  in the S-OWODB split

### ISSUE THREAD

**Issue by yuki1ssad** [orrzohar/PROB#52]
Hello, thank you for your excellent work. Could you please provide WI and AOSE of your model PROB in the S-OWODB split? Looking forward to your reply, thank you.

**Comment by orrzohar** [comment]
Hi @yuki1ssad,
I am sorry, I no longer have the logs for that, but it should be very easy to run an evaluation on the S-OWODB.
Have you been able to set up the environment? 
Eval shouldn't take very long. 
Best,
Orr
