### ISSUE TITLE
Treat "unknown" class.

### ISSUE THREAD

**Issue by 4ursmile** [orrzohar/PROB#54]
Thank you for the great work; it's inspired me for my next research! 
I got confused when I read through your paper and your code. I can't see where you handle predicting an object as unknown. I noticed you mentioned there are 80 classes in total, but in your code, there are 81 classes. Do you use it as an 'unknown' class, or are you performing some handcrafted post-processing to consider an object as 'unknown'?

**Comment by orrzohar** [comment]
Hi @4ursmile,

Class prediction is 81 classes as we have 80 known objects classes + unknown objects. Prediction is somewhat split between the model's forward pass + the PostProcessor object. These are the primary components of unknown object prediction:

## Unknown object prediction head:

https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/models/prob_deformable_detr.py#L66-L79

## Model's forward pass 
(only the parts that dead with prob. objecness)

https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/models/prob_deformable_detr.py#L251

https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/models/prob_deformable_detr.py#L260

https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/models/prob_deformable_detr.py#L272

https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/models/prob_deformable_detr.py#L276

https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/models/prob_deformable_detr.py#L278



## Post Processor:

https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/models/prob_deformable_detr.py#L531-L534



However, I would look at all three in their entirety for a comprehensive understanding of the class prediction. Note that we train the last (81st) logit to be the unknown objects + background (i.e., everything besides known objects) logit, and then utilize the objectness to filter all the background queries.

**Comment by 4ursmile** [comment]
Thank for your answer @orrzohar. I understand the concept of using an additional class for unknown objects. I assume you train with 81 classes for the four tasks, and in the post-processing phase, you only consider classes using a filter. Am I correct?
> ## Post Processor:
> https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/models/prob_deformable_detr.py#L526

But I still get confused. Can you help me more?

Unlike previous work, your method uses probabilistic objectness to train the model, so it can distinguish between background and foreground. Therefore, we don't need to use "unknown" as a pseudo-class during training, as you mentioned in your paper. My question is, if we don't need to include the "unknown" class in the training process, how can the classification head classify an object as unknown? I noticed you putted sigmoid_focal_loss at the beginning of [prob_deformable_detr.py](https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/models/prob_deformable_detr.py#L35). Does this involve some tricky to train the classification head to handle unknown objects?

**Comment by orrzohar** [comment]
Hi @4ursmile,

Think of the `unknown' logit as a `not known object' logit. The probabilistic objectness head separates objects and background. Meanwhile, the 'unknown' logit (which we train on all non-matches object proposals) effectively separates the known objects and everything else (like OOD detection). 

I have a figure in my appendix that is informative. You can also think of it this way: when predicting a class, we calculate:

$p_{logit} \cdot p_{object}$

If you don't have an `unknown object' logit -- you are effectively assuming that $p_{logit}[unknown]$ always equals 1. In the end, to make a prediction, we take the top-k class values and don't have a separate protocol for known and unknown class predictions.

Best,
Orr
