### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Aaron-huangyangyang** [orrzohar/PROB#56]
FileNotFoundError: [Errno 2] No such file or directory: './data/OWOD/JPEGImages/3436.jpg'

**Comment by orrzohar** [comment]
Hi @Aaron-huangyangyang,
it seems like you did not set up your dataset properly. Did you make sure to include VOC2012/VOC2007 as described in the README?

**Comment by Aaron-huangyangyang** [comment]
Dear author, thank you very much for your reply, I am in accordance with the GCP_setup/setup_4. Sh set data sets, but my path is/home/mrp/HYY/PROBWORKPLACE/PROB/data/OWOD, how do I modify it, looking forward to your reply

**Comment by orrzohar** [comment]
Hi @Aaron-huangyangyang 
Just download the pascal Voc images and add them to JPEGImages
