### ISSUE TITLE
Questions when applying PROB on new dataset

### ISSUE THREAD

**Issue by luckylukez** [orrzohar/PROB#59]
Hi Orr, I am trying to apply PROB to my own dataset and I have a couple questions:

I have seen you recommend to tune the objectness temperature. Could you explain a bit what it is and hod does it affect predictions? If i keep pred_per_image constant I will always get the same amount of predictions anyway right?

How many instances of a new class is sufficient to learn a reasonable mAP?

Thanks!

**Comment by luckylukez** [comment]
It seems in this code that the temperature is just a constant applied to the objectness prediction. Is that correct?
In Postprocess.forward():
```
out_logits, pred_obj, out_bbox = outputs['pred_logits'], outputs['pred_obj'], outputs['pred_boxes']
out_logits[:,:, self.invalid_cls_logits] = -10e10

assert len(out_logits) == len(target_sizes)
assert target_sizes.shape[1] == 2

obj_prob = torch.exp(-self.temperature*pred_obj).unsqueeze(-1)
prob = obj_prob*out_logits.sigmoid()
```

**Comment by orrzohar** [comment]
hi @luckylukez,

the obj temperature is tunable by changing:

https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/main_open_world.py#L148

The objectness temperature effectively scales how much priority probabilistic objectness has. I tired to neutralize how important this hyper parameter is by dividing it by the hidden dimension:

https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/models/prob_deformable_detr.py#L639

Default value is 1.3. In the Appendix of my manuscript, I showed the effect that this parameter has on U-Recall and K-mAP. 
<img width="428" alt="image" src="https://github.com/orrzohar/PROB/assets/108689663/d71374bf-7953-440a-8739-4a1c0e98eb00">


You are correct, the objectness temperature multiplies the probabilistic objectness:

<img width="428" alt="image" src="https://github.com/orrzohar/PROB/assets/108689663/69439eee-aa35-4082-aaa5-605aa41f19f7">


Best,
Orr

**Comment by luckylukez** [comment]
Thanks Orr,

Do you have any thoughts on my other question? How many instances of a new class do you think is necessary for PROB to learn a reasonable mAP?

**Comment by orrzohar** [comment]
Hi @luckylukez,

I have been thinking about this. I think, generally, this will be affected by how similar the objects are to existing objects. In the current benchmarks, as they are COCO-based, you have really used a lot of data instances. This is as if you are training a model from scratch (on the order of at least ~5K images, but this is a guess). 


Best,
Orr
