### ISSUE TITLE
Thoughts on final prediction

### ISSUE THREAD

**Issue by luckylukez** [orrzohar/PROB#60]
Hi Orr,

I have a couple thoughts on the final prediction and would love to hear your thoughts. 

If I understand things correctly the C+1 logit of the classification head is the logit for "not known" objects, which can be either unknown or background. The objectness head on the other hand, learns a general objectness from the known classes in order to give a higher objectness score to objects that are known or similar to known objects. The objects that are similar to known objects but not known are what we hope will match with unknown objects that are not background. Is that a fair description?

My thought is this: The objectness head will score higher for objects similar to known classes, but the C+1 logit might score higher the less similar an object is to any known object as it is essentially a score of "not known". So when detecting unknowns, there could be a risk that objects that are less similar to knowns actually achieve higher scores simply because the C+1 logit is high. In that case maybe it would be reasonable to let the classification head sort unknowns from knowns, but then let the final score of the unknowns be just the score from the objectness head as this should favor objects more similar to known objects. 

Any thoughts on this?

**Comment by orrzohar** [comment]
Hi @luckylukez,

Sorry for the belated reply. I actually agree very much with what you say. Perhaps a 'threshold' should be applied on the cls head output so once a proposal is classified as an 'object', it does not affect prediction anymore (this would, unfortunately, introduce another hyperparameter). I also think that objects that are _similar_ to the known objects are more likely to be of interest to a potential user than ones that are dis-similar. 

In a recent work of mine, I explicitly defined unknown object as objects that share visual/functional attributes with the known objects. Maybe give that a look? 
https://github.com/orrzohar/FOMO

Best,
Orr

**Comment by luckylukez** [comment]
Hi Orr, thank you very much for answering!

I was not sure I had understood the model correctly, so thanks for clearing that up.

Best,
Lukas

**Comment by orrzohar** [comment]
Hi @luckylukez,

Okay, in any case -- I think your intuition is correct. I will say that for traditional OWODB benchmarks - especially S-OWODB - the unknown and unknown classes _are_ disjointed (in the case of S-OWODB, the unknown and know objects are from literally different superclasses). [Hyp-OW](https://arxiv.org/pdf/2306.14291) looked into this as well.

Best,
Orr
