### ISSUE TITLE
Distributed initialisation failure

### ISSUE THREAD

**Issue by yangengineering** [orrzohar/PROB#62]
Firstly thank you very much for your work, I followed your documentation step by step to configure the data, models etc. But I am having a problem with the distribution initialisation getting stuck while running bash run.sh, which is very disturbing for me. 

![微信图片_20240627182347](https://github.com/orrzohar/PROB/assets/117337127/5dfd77c9-b90d-45fe-be9e-c84ae390e56b)

**Comment by yangengineering** [comment]
![Uploading 微信图片_20240627182347.png…]()

**Comment by yangengineering** [comment]
![微信图片_20240627182347](https://github.com/orrzohar/PROB/assets/117337127/a33b5fe4-42c9-442e-843f-640554e2f5d5)

**Comment by yangengineering** [comment]
I have finished it by pressing enter when it appeared.

**Comment by orrzohar** [comment]
Hi @yangengineering,
You did not log into wandb. For how to log in:
https://docs.wandb.ai/quickstart
Best,
orr
