### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by yangengineering** [orrzohar/PROB#63]
Hello, thank you very much for open-sourcing your code. But after I run it according to your run.sh, I used 4 3090's with 24g RTX cards and the batchsize is only 1 each, but why does he still report exceeding memory after a period of normal operation, and why was it ok in the beginning but not now. 
![微信图片_20240627185741](https://github.com/orrzohar/PROB/assets/117337127/53080368-b383-4e8e-abb6-4cbd85db8419)

**Comment by orrzohar** [comment]
Hi @yangengineering,

Please see Issue https://github.com/orrzohar/PROB/issues/48, where we troubleshooted running 4x3090's

Best,
Orr
