### ISSUE TITLE
OSError: [Errno 8] Exec format error: 'configs/EVAL_M_OWOD_BENCHMARK.sh'

### ISSUE THREAD

**Issue by simranbajaj06** [orrzohar/PROB#65]
Objective: I am trying to perform direct inference without training the model 

After setting up the environment and installing all dependencies,also I had made some changes required to run this code on single instance ,and i have added the weights in the mentioned folder then I encounter the following error when attempting to run the run_eval.sh script:
OSError: [Errno 8] Exec format error: 'configs/EVAL_M_OWOD_BENCHMARK.sh'

Environment: Single EC2 instance . [Tesla T4]
Script: run_eval.sh
@orrzohar

**Comment by orrzohar** [comment]
It seems like you are trying to run a the shell script (`configs/EVAL_M_OWOD_BENCHMARK.sh`) as an executable, which is causing the `OSError: [Errno 8] Exec format error` error.

To resolve this issue, you need to make sure that the script has execute permissions and is being run as a shell script. Here are the steps you can follow:

1. Make sure that the script has execute permissions:
```bash
chmod +x configs/EVAL_M_OWOD_BENCHMARK.sh
```
2. Run the script with the appropriate shell:
```bash
bash configs/EVAL_M_OWOD_BENCHMARK.sh
```
If you encounter any other errors, please provide more information about your environment and the changes you made to the code so I can better assist you.

**Comment by simranbajaj06** [comment]
now its working thank you!! @orrzohar
