### ISSUE TITLE
diff between 'ProbObjectnessHead' and 'FullProbObjectnessHead'

### ISSUE THREAD

**Issue by ezyzzy** [orrzohar/PROB#66]
In the PROB model, I noticed two modules, 'ProbObjectnessHead' and 'FullProbObjectnessHead'.
I have two questions:
1. Only the former is used, but I believe the latter is more in line with the description in the paper. Why was the former used instead of the latter?
2. The paper mentions that the module for calculating the Objectness score will be trained in stages, but I don't seem to find how this step is handled.
I hope to get your answers!

**Comment by orrzohar** [comment]
Hi @ezyzzy,

regarding (1) - this is a question of whether or not you make the IID assumption:
<img width="476" alt="image" src="https://github.com/user-attachments/assets/0b6d7ea5-3634-4674-95ad-dc5933a63b61">


regarding (2): please see https://github.com/orrzohar/PROB/issues/7
