### ISSUE TITLE
some questions about the article

### ISSUE THREAD

**Issue by Antonwxb** [orrzohar/PROB#67]
Hello, I've just read your great work, but i have some little questions about the article:
1. I can't figure out how you discriminate the unknown from known classes. The figure 2(overview of PROB) shows that **fcls** outputs a vector with K^t dimensions, but become (K^t + 1) dimensions just after multiplying the output of **fobj**, which is a single number I think. It's quite confusing.
2. I think the objectness loss can't prevent the query embeddings (not matched) from getting closer to the mean of the modeled Gaussian distribution, for there is no penalty for them, which may cause the increasing of false positives(the wrong detections which is actually background) in the test time.
Can you share some opinions to these questions? great thank to that.

**Comment by orrzohar** [comment]
Hi @Antonwxb,
1. The reason I put K^t there was to highlight that you apply the loss on known classes, however, you are correct that fcls outputs a K^t+1 vector and that the loss is applied on a K^t+1 vector. Know and known classes are descriminated via the classification head, which classifies objects into one of the known objects or unknown + background queries. 
2. This does not happen, as you account for the distribution of all queries. If all quries were predicted to be the same, then the loss would go up not down. You effectively are normalizing for the query distribution before applying the loss, negating this effect. The effect is that the background quries have the same 'mean' but higher variance w.r.t. the unknown objects. 
<img width="315" alt="image" src="https://github.com/user-attachments/assets/c7bddc0b-ce4d-4199-a3f9-889b7faac33a">


here is a TSNE of the embedding space, note that in the left only `labeled' unknown objects are labeled, so meny gray down in the center may legiitmately be unknown objects that are not labeled (not one of the 80 classes labeled in COCO).

LMK if this clarfies,
Orr

**Comment by Antonwxb** [comment]
your reply really helps. thanks a lot!
