### ISSUE TITLE
IOD 

### ISSUE THREAD

**Issue by Wang0203** [orrzohar/PROB#8]
Hello. How to trian "19+1" , "15+5" and "10+10" settings?

**Comment by orrzohar** [comment]
Hi Wang,
You can do this by changing the "--PREV_INTRODUCED_CLS" and "--CUR_INTRODUCED_CLS" in the provided bash scripts -- I don't have the originals anymore, but I will be able to come back and reproduce them in ~2-3 weeks. 

I will note that these results depend on the "num_inst_per_class" inputs, so the easiest thing to do is increase this to like 60, and then the performance saturates. I don't see PROB as a method that improves iOD in a significant way as it uses exemplar replay, which betrays the assumptions of a lot of iOD works where no storage is allowed - but for OWOD, it seems to be practical. 

Best,
Orr

**Comment by orrzohar** [comment]
Hi @Wang0203,
The commands you need to use are along these lines: 

```
python -u main_open_world.py \
    --output_dir "exps/IL/19_1" --dataset VOC2007 --PREV_INTRODUCED_CLS 0 --CUR_INTRODUCED_CLS 19\
    --train_set 'voc2007_trainval' --test_set 'voc2007_test' --epochs 61\
    --model_type 'prob' --obj_loss_coef 8e-4 --obj_temp 1.3\
    --wandb_name "${WANDB_NAME}_t1" --exemplar_replay_selection --num_inst_per_class 60\
    --exemplar_replay_dir ${WANDB_NAME} --exemplar_replay_cur_file "IL_19_ft.txt"\
    ${PY_ARGS}    
    
    
python -u main_open_world.py \
    --output_dir "exps/IL/19_1"  --dataset VOC2007 --PREV_INTRODUCED_CLS 19 --CUR_INTRODUCED_CLS 20\
    --train_set 'voc2007_trainval' --test_set 'voc2007_test' --epochs 81\
    --model_type 'prob' --obj_loss_coef 8e-4 --obj_temp 1.3\
    --wandb_name "${WANDB_NAME}_t1" --exemplar_replay_selection --num_inst_per_class 60\
    --exemplar_replay_dir ${WANDB_NAME}\
    --exemplar_replay_prev_file "IL_19_ft.txt" --exemplar_replay_cur_file "IL_19_1_ft.txt"\
    --pretrain "exps/IL/19_1/checkpoint0060.pth" --lr 2e-5\
    ${PY_ARGS}  
    
    
python -u main_open_world.py \
    --output_dir "exps/IL/19_1"  --dataset VOC2007 --PREV_INTRODUCED_CLS 19 --CUR_INTRODUCED_CLS 20\
    --train_set 'IL_19_1_ft' --test_set 'voc2007_test' --epochs 151\
    --model_type 'prob' --obj_loss_coef 8e-4 --obj_temp 1.3\
    --wandb_name "${WANDB_NAME}_t1" \
    --pretrain "exps/IL/19_1/checkpoint0080.pth"\
    ${PY_ARGS} 
```
If you want to run the 15+5/10+10 experiments, the PREV_INTRODUCED_CLS \ CUR_INTRODUCED_CLS  will need to be changed accordingly.

I will stress that the number of training epochs/number of inst per class/objectness temperature need to be tuned to reproduce the results in the paper. 

Hope this helps!
Orr

**Comment by Taoxiaohei** [comment]
hello, do you know where can i get the file ./data/OWOD/ImageSets/VOC2007/IL_19_1_ft.txt, should i make it myself according to the voc2007_trainval.txt? i am looking forward to your reply, thank you !
