### ISSUE TITLE
The download link of  pretrain weights is invalid.

### ISSUE THREAD

**Issue by harrylin-hyl** [orrzohar/PROB#9]
The download link of  pretrain weights is invalid. Please pull a new link, thanks!

**Comment by orrzohar** [comment]
Hi,
I just tested the download link and believe it is valid, i.e., I could download the weights without issue. 

Could you provide more details on how you are attempting to download the weights and what output you see?

**Comment by harrylin-hyl** [comment]
Now, I can open the download link. Thanks!
